### PR TITLE
UI Fix on monthlyLeaderboardScreen

### LINKED ISSUE #287: Task: UI Fix on Monthly Leaderboard

### PR DESCRIPTION
**Pull request by solo-daemon**
fix #287

### CODE REVIEW

**Comment by letsintegreat** [comment]
Neither issue nor PR includes what exactly is fixed, can you please brief on that a little bit?

**Comment by solo-daemon** [comment]
@just-ary27 @fredfalcon 

There was a alignment fix and font changes. A basic text will be shown for when there is no data related to that month, on the leaderboard screen 

https://user-images.githubusercontent.com/65587505/230460186-a99515f0-74e3-4ea1-aa65-d0debfd461d3.mp4

**Review by just-ary27 — CHANGES_REQUESTED** [review]
Could you put the text in a card? Looking not that great rn

**Comment by solo-daemon** [comment]
> Could you put the text in a card? Looking not that great rn

Sure

**Comment by solo-daemon** [comment]
@just-ary27 

https://user-images.githubusercontent.com/65587505/230494389-a97ce090-5187-4af8-adda-0af563ca5797.mp4

**Comment by solo-daemon** [comment]
https://github.com/OWASP/BLT-Flutter/issues/287#issuecomment-1499663573

@fredfalcon done

**Review by DonnieBLT — APPROVED** [review]

**Pull request closed without merging**
