### PR TITLE
Update Usage of barrel Imports issue

### LINKED ISSUE #302: Task: Update Usage of barrel Imports
Currently project uses normal imports.

May we use barrel imports like a single file for each folders where files in it are exported? It will result in cleaner imports and reduce clutter in files with large number of imports.

### PR DESCRIPTION
**Pull request by Uttkarsh-raj**
This pull request fixes #302 . Please review the changes if any needed.

### CODE REVIEW

**Review by DonnieBLT — APPROVED** [review]

**Review by DonnieBLT — CHANGES_REQUESTED** [review]
Can you please update this to work with the localization code that was added recently?

**Comment by Uttkarsh-raj** [comment]
> Can you please update this to work with the localization code that was added recently?

Working on it.. by the way i dont know what has happened but the new code pushed is having the following errors...
<div style="display:flex">
 </img>
 </img>
<div>

**Comment by Dante291** [comment]
take a latest fetch and it will work fine

**Comment by Uttkarsh-raj** [comment]
> take a latest fetch and it will work fine

i did but its the same..

**Comment by Uttkarsh-raj** [comment]
@DonnieBLT i have made the required changes.. Can you review it and tell if there are any other?

**Review by DonnieBLT — APPROVED** [review]
Looks good to me

**Comment by DonnieBLT** [comment]
error • Undefined name 'darkModeProvider' • lib/src/pages/home/issues.dart:54:34 • undefined_identifier

**Comment by Dante291** [comment]
This error could be because you've not imported the file which have darkModeProvider

**Comment by Uttkarsh-raj** [comment]
@DonnieBLT the changes have been made and ready to merge with all conflicts resolved...

**Comment by DonnieBLT** [comment]
Thank you!

**Pull request merged**
