### PR TITLE
Fixing range error when no screenShot for issue is there

### LINKED ISSUE #356: Fix valid range issue
image

### PR DESCRIPTION
**Pull request by Dante291**
fixes #356 

Basically we were getting range error because we were trying to access first element of screenshots list of an issue which was null so I added a null check such that if list is null we show a default issue image.

Screenshot_1708799047

### CODE REVIEW

**Comment by Dante291** [comment]
@DonnieBLT Let me know if this default image (bug image which matches BLT theme) for an issue with no screenshots is ok?

**Comment by DonnieBLT** [comment]
There should be no issues without screenshots. That's a bug that we've been having that needs to be fixed so I think what we can do instead is just don't show the issue. How about that?

**Comment by Dante291** [comment]
> There should be no issues without screenshots. That's a bug that we've been having that needs to be fixed so I think what we can do instead is just don't show the issue. How about that?

Alright then we need a check to see if there is any screenshot for a issue, if no then dont show that issue also should i add a functionnality in the app that user shouldn't be able to create an issue if there is no screenshot attached?

**Comment by DonnieBLT** [comment]
That would be good. Thanks so much.

**Pull request closed without merging**
